#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

COMMAND=rush prettier-fix

echo --------------------------------------------
echo Starting Git hook: pre-commit

echo Invoking $COMMAND
$COMMAND

echo Finished Git hook: pre-commit
echo --------------------------------------------
