// THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT CHANGE DIRECTLY

import { DOMAttribute, DOMEventHandler } from './value'
import { MoodAttributes } from './mood_attributes'

export type DOMAttributes<State, Action, El> = Record<
  string,
  DOMAttribute<State, Action> | DOMEventHandler<State, Event, Action>
> & MoodAttributes<State, El>
