/*
Copyright 2019 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    https://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import { el2 } from './element'

export const a = el2('a')
export const abbr = el2('abbr')
export const address = el2('address')
export const applet = el2('applet')
export const area = el2('area')
export const article = el2('article')
export const aside = el2('aside')
export const audio = el2('audio')
export const b = el2('b')
export const base = el2('base')
export const basefont = el2('basefont')
export const bdi = el2('bdi')
export const bdo = el2('bdo')
export const blockquote = el2('blockquote')
export const body = el2('body')
export const br = el2('br')
export const button = el2('button')
export const canvas = el2('canvas')
export const caption = el2('caption')
export const cite = el2('cite')
export const code = el2('code')
export const col = el2('col')
export const colgroup = el2('colgroup')
export const data = el2('data')
export const datalist = el2('datalist')
export const dd = el2('dd')
export const del = el2('del')
export const details = el2('details')
export const dfn = el2('dfn')
export const dialog = el2('dialog')
export const dir = el2('dir')
export const div = el2('div')
export const dl = el2('dl')
export const dt = el2('dt')
export const em = el2('em')
export const embed = el2('embed')
export const fieldset = el2('fieldset')
export const figcaption = el2('figcaption')
export const figure = el2('figure')
export const font = el2('font')
export const footer = el2('footer')
export const form = el2('form')
export const frame = el2('frame')
export const frameset = el2('frameset')
export const h1 = el2('h1')
export const h2 = el2('h2')
export const h3 = el2('h3')
export const h4 = el2('h4')
export const h5 = el2('h5')
export const h6 = el2('h6')
export const head = el2('head')
export const header = el2('header')
export const hgroup = el2('hgroup')
export const hr = el2('hr')
export const html = el2('html')
export const i = el2('i')
export const iframe = el2('iframe')
export const img = el2('img')
export const input = el2('input')
export const ins = el2('ins')
export const kbd = el2('kbd')
export const label = el2('label')
export const legend = el2('legend')
export const li = el2('li')
export const link = el2('link')
export const listing = el2('listing')
export const main = el2('main')
export const map = el2('map')
export const mark = el2('mark')
export const marquee = el2('marquee')
export const menu = el2('menu')
export const meta = el2('meta')
export const meter = el2('meter')
export const nav = el2('nav')
export const noscript = el2('noscript')
export const object = el2('object')
export const ol = el2('ol')
export const optgroup = el2('optgroup')
export const option = el2('option')
export const output = el2('output')
export const p = el2('p')
export const param = el2('param')
export const picture = el2('picture')
export const pre = el2('pre')
export const progress = el2('progress')
export const q = el2('q')
export const rp = el2('rp')
export const rt = el2('rt')
export const ruby = el2('ruby')
export const s = el2('s')
export const samp = el2('samp')
export const script = el2('script')
export const section = el2('section')
export const select = el2('select')
export const slot = el2('slot')
export const small = el2('small')
export const source = el2('source')
export const span = el2('span')
export const strong = el2('strong')
export const style = el2('style')
export const sub = el2('sub')
export const summary = el2('summary')
export const sup = el2('sup')
export const table = el2('table')
export const tbody = el2('tbody')
export const td = el2('td')
export const template = el2('template')
export const textarea = el2('textarea')
export const tfoot = el2('tfoot')
export const th = el2('th')
export const thead = el2('thead')
export const time = el2('time')
export const title = el2('title')
export const tr = el2('tr')
export const track = el2('track')
export const u = el2('u')
export const ul = el2('ul')
export const varEl = el2('var')
export const video = el2('video')
export const wbr = el2('wbr')
export const xmp = el2('xmp')
