import { DOMAttribute, DOMEventHandler } from './value'
import { CSSProperties } from './css_properties'
import { MoodAttributes } from './mood_attributes'

export interface DOMAttributes<State, Action, El> extends MoodAttributes<State, El> {
  abbr?: DOMAttribute<State, string>
  accept?: DOMAttribute<State, string>
  acceptCharset?: DOMAttribute<State, string>
  accessKey?: DOMAttribute<State, string>
  action?: DOMAttribute<State, string>
  allow?: DOMAttribute<State, string>
  allowFullscreen?: DOMAttribute<State, boolean>
  allowPaymentRequest?: DOMAttribute<State, boolean>
  alt?: DOMAttribute<State, string>
  as?: DOMAttribute<State, string>
  async?: DOMAttribute<State, boolean>
  autocapitalize?: DOMAttribute<State, string>
  autocomplete?: DOMAttribute<State, string>
  autofocus?: DOMAttribute<State, boolean>
  autoplay?: DOMAttribute<State, boolean>
  bgProperties?: DOMAttribute<State, string>
  checked?: DOMAttribute<State, boolean>
  cite?: DOMAttribute<State, string>
  className?: DOMAttribute<State, string>
  colSpan?: DOMAttribute<State, number>
  color?: DOMAttribute<State, string>
  cols?: DOMAttribute<State, number>
  content?: DOMAttribute<State, string>
  contentEditable?: DOMAttribute<State, string>
  controls?: DOMAttribute<State, boolean>
  coords?: DOMAttribute<State, string>
  crossOrigin?: DOMAttribute<State, string>
  currentScale?: DOMAttribute<State, number>
  currentTime?: DOMAttribute<State, number>
  data?: DOMAttribute<State, string>
  dateTime?: DOMAttribute<State, string>
  decoding?: DOMAttribute<State, 'async' | 'sync' | 'auto'>
  default?: DOMAttribute<State, boolean>
  defaultChecked?: DOMAttribute<State, boolean>
  defaultMuted?: DOMAttribute<State, boolean>
  defaultPlaybackRate?: DOMAttribute<State, number>
  defaultSelected?: DOMAttribute<State, boolean>
  defaultValue?: DOMAttribute<State, string>
  defer?: DOMAttribute<State, boolean>
  dir?: DOMAttribute<State, string>
  dirName?: DOMAttribute<State, string>
  disabled?: DOMAttribute<State, boolean>
  download?: DOMAttribute<State, string>
  draggable?: DOMAttribute<State, boolean>
  encoding?: DOMAttribute<State, string>
  enctype?: DOMAttribute<State, string>
  files?: DOMAttribute<State, FileList | null>
  formAction?: DOMAttribute<State, string>
  formEnctype?: DOMAttribute<State, string>
  formMethod?: DOMAttribute<State, string>
  formNoValidate?: DOMAttribute<State, boolean>
  formTarget?: DOMAttribute<State, string>
  hash?: DOMAttribute<State, string>
  headers?: DOMAttribute<State, string>
  height?: DOMAttribute<State, number | string>
  hidden?: DOMAttribute<State, boolean>
  high?: DOMAttribute<State, number>
  host?: DOMAttribute<State, string>
  hostname?: DOMAttribute<State, string>
  href?: DOMAttribute<State, string>
  hreflang?: DOMAttribute<State, string>
  htmlFor?: DOMAttribute<State, string>
  httpEquiv?: DOMAttribute<State, string>
  id?: DOMAttribute<State, string>
  imageSizes?: DOMAttribute<State, string>
  imageSrcset?: DOMAttribute<State, string>
  indeterminate?: DOMAttribute<State, boolean>
  inputMode?: DOMAttribute<State, string>
  integrity?: DOMAttribute<State, string>
  isMap?: DOMAttribute<State, boolean>
  kind?: DOMAttribute<State, string>
  label?: DOMAttribute<State, string>
  lang?: DOMAttribute<State, string>
  length?: DOMAttribute<State, number>
  loop?: DOMAttribute<State, boolean>
  low?: DOMAttribute<State, number>
  max?: DOMAttribute<State, number | string>
  maxLength?: DOMAttribute<State, number>
  media?: DOMAttribute<State, string>
  method?: DOMAttribute<State, string>
  min?: DOMAttribute<State, number | string>
  minLength?: DOMAttribute<State, number>
  msAudioCategory?: DOMAttribute<State, string>
  msAudioDeviceType?: DOMAttribute<State, string>
  msHorizontalMirror?: DOMAttribute<State, boolean>
  msPlayToDisabled?: DOMAttribute<State, boolean>
  msPlayToPreferredSourceUri?: DOMAttribute<State, string>
  msPlayToPrimary?: DOMAttribute<State, boolean>
  msRealTime?: DOMAttribute<State, boolean>
  msStereo3DPackingMode?: DOMAttribute<State, string>
  msStereo3DRenderMode?: DOMAttribute<State, string>
  msZoom?: DOMAttribute<State, boolean>
  multiple?: DOMAttribute<State, boolean>
  muted?: DOMAttribute<State, boolean>
  name?: DOMAttribute<State, string>
  noModule?: DOMAttribute<State, boolean>
  noValidate?: DOMAttribute<State, boolean>
  nonce?: DOMAttribute<State, string>
  onMSVideoFormatChanged?: DOMEventHandler<State, Event, Action>
  onMSVideoFrameStepCompleted?: DOMEventHandler<State, Event, Action>
  onMSVideoOptimalLayoutChanged?: DOMEventHandler<State, Event, Action>
  onabort?: DOMAttribute<State, Event>
  onafterprint?: DOMAttribute<State, Event>
  onanimationcancel?: DOMAttribute<State, Event>
  onanimationend?: DOMAttribute<State, Event>
  onanimationiteration?: DOMAttribute<State, Event>
  onanimationstart?: DOMAttribute<State, Event>
  onauxclick?: DOMAttribute<State, Event>
  onbeforeprint?: DOMAttribute<State, Event>
  onbeforeunload?: DOMEventHandler<State, BeforeUnloadEvent, Action>
  onblur?: DOMAttribute<State, Event>
  oncancel?: DOMAttribute<State, Event>
  oncanplay?: DOMAttribute<State, Event>
  oncanplaythrough?: DOMAttribute<State, Event>
  onchange?: DOMAttribute<State, Event>
  onclick?: DOMAttribute<State, Event>
  onclose?: DOMAttribute<State, Event>
  oncontextmenu?: DOMAttribute<State, Event>
  oncopy?: DOMAttribute<State, Event>
  oncuechange?: DOMAttribute<State, Event>
  oncut?: DOMAttribute<State, Event>
  ondblclick?: DOMAttribute<State, Event>
  ondrag?: DOMAttribute<State, Event>
  ondragend?: DOMAttribute<State, Event>
  ondragenter?: DOMAttribute<State, Event>
  ondragexit?: DOMAttribute<State, Event>
  ondragleave?: DOMAttribute<State, Event>
  ondragover?: DOMAttribute<State, Event>
  ondragstart?: DOMAttribute<State, Event>
  ondrop?: DOMAttribute<State, Event>
  ondurationchange?: DOMAttribute<State, Event>
  onemptied?: DOMAttribute<State, Event>
  onencrypted?: DOMAttribute<State, Event>
  onended?: DOMAttribute<State, Event>
  onerror?: DOMEventHandler<State, ErrorEvent, Action>
  onfocus?: DOMAttribute<State, Event>
  onfullscreenchange?: DOMAttribute<State, Event>
  onfullscreenerror?: DOMAttribute<State, Event>
  ongotpointercapture?: DOMAttribute<State, Event>
  onhashchange?: DOMAttribute<State, Event>
  oninput?: DOMAttribute<State, Event>
  oninvalid?: DOMAttribute<State, Event>
  onkeydown?: DOMAttribute<State, Event>
  onkeypress?: DOMAttribute<State, Event>
  onkeyup?: DOMAttribute<State, Event>
  onlanguagechange?: DOMAttribute<State, Event>
  onload?: DOMAttribute<State, Event>
  onloadeddata?: DOMAttribute<State, Event>
  onloadedmetadata?: DOMAttribute<State, Event>
  onloadend?: DOMAttribute<State, Event>
  onloadstart?: DOMAttribute<State, Event>
  onlostpointercapture?: DOMAttribute<State, Event>
  onmessage?: DOMAttribute<State, Event>
  onmessageerror?: DOMAttribute<State, Event>
  onmousedown?: DOMAttribute<State, Event>
  onmouseenter?: DOMAttribute<State, Event>
  onmouseleave?: DOMAttribute<State, Event>
  onmousemove?: DOMAttribute<State, Event>
  onmouseout?: DOMAttribute<State, Event>
  onmouseover?: DOMAttribute<State, Event>
  onmouseup?: DOMAttribute<State, Event>
  onoffline?: DOMAttribute<State, Event>
  ononline?: DOMAttribute<State, Event>
  onpagehide?: DOMAttribute<State, Event>
  onpageshow?: DOMAttribute<State, Event>
  onpaste?: DOMAttribute<State, Event>
  onpause?: DOMAttribute<State, Event>
  onplay?: DOMAttribute<State, Event>
  onplaying?: DOMAttribute<State, Event>
  onpointercancel?: DOMAttribute<State, Event>
  onpointerdown?: DOMAttribute<State, Event>
  onpointerenter?: DOMAttribute<State, Event>
  onpointerleave?: DOMAttribute<State, Event>
  onpointermove?: DOMAttribute<State, Event>
  onpointerout?: DOMAttribute<State, Event>
  onpointerover?: DOMAttribute<State, Event>
  onpointerup?: DOMAttribute<State, Event>
  onpopstate?: DOMAttribute<State, Event>
  onprogress?: DOMAttribute<State, Event>
  onratechange?: DOMAttribute<State, Event>
  onrejectionhandled?: DOMAttribute<State, Event>
  onreset?: DOMAttribute<State, Event>
  onresize?: DOMAttribute<State, Event>
  onscroll?: DOMAttribute<State, Event>
  onsecuritypolicyviolation?: DOMAttribute<State, Event>
  onseeked?: DOMAttribute<State, Event>
  onseeking?: DOMAttribute<State, Event>
  onselect?: DOMAttribute<State, Event>
  onselectionchange?: DOMAttribute<State, Event>
  onselectstart?: DOMAttribute<State, Event>
  onstalled?: DOMAttribute<State, Event>
  onstorage?: DOMAttribute<State, Event>
  onsubmit?: DOMAttribute<State, Event>
  onsuspend?: DOMAttribute<State, Event>
  ontimeupdate?: DOMAttribute<State, Event>
  ontoggle?: DOMAttribute<State, Event>
  ontouchcancel?: DOMAttribute<State, Event>
  ontouchend?: DOMAttribute<State, Event>
  ontouchmove?: DOMAttribute<State, Event>
  ontouchstart?: DOMAttribute<State, Event>
  ontransitioncancel?: DOMAttribute<State, Event>
  ontransitionend?: DOMAttribute<State, Event>
  ontransitionrun?: DOMAttribute<State, Event>
  ontransitionstart?: DOMAttribute<State, Event>
  onunhandledrejection?: DOMAttribute<State, Event>
  onunload?: DOMEventHandler<State, Event | EventHandlerNonNull, Action>
  onvolumechange?: DOMAttribute<State, Event>
  onwaiting?: DOMAttribute<State, Event>
  onwaitingforkey?: DOMAttribute<State, Event>
  onwheel?: DOMAttribute<State, Event>
  onzoom?: DOMEventHandler<State, Event, Action>
  open?: DOMAttribute<State, boolean>
  optimum?: DOMAttribute<State, number>
  password?: DOMAttribute<State, string>
  pathname?: DOMAttribute<State, string>
  pattern?: DOMAttribute<State, string>
  ping?: DOMAttribute<State, string>
  placeholder?: DOMAttribute<State, string>
  playbackRate?: DOMAttribute<State, number>
  port?: DOMAttribute<State, string>
  poster?: DOMAttribute<State, string>
  preload?: DOMAttribute<State, string>
  protocol?: DOMAttribute<State, string>
  readOnly?: DOMAttribute<State, boolean>
  referrerPolicy?: DOMAttribute<State, string | ReferrerPolicy>
  rel?: DOMAttribute<State, string>
  required?: DOMAttribute<State, boolean>
  returnValue?: DOMAttribute<State, string>
  reversed?: DOMAttribute<State, boolean>
  rowSpan?: DOMAttribute<State, number>
  rows?: DOMAttribute<State, number>
  scope?: DOMAttribute<State, string>
  scrollLeft?: DOMAttribute<State, number>
  scrollTop?: DOMAttribute<State, number>
  search?: DOMAttribute<State, string>
  selected?: DOMAttribute<State, boolean>
  selectedIndex?: DOMAttribute<State, number>
  selectionDirection?: DOMAttribute<State, string>
  selectionEnd?: DOMAttribute<State, number>
  selectionStart?: DOMAttribute<State, number>
  shape?: DOMAttribute<State, string>
  size?: DOMAttribute<State, number>
  sizes?: DOMAttribute<State, string>
  slot?: DOMAttribute<State, string>
  span?: DOMAttribute<State, number>
  spellcheck?: DOMAttribute<State, boolean>
  src?: DOMAttribute<State, string>
  srcObject?: DOMAttribute<State, MediaStream | MediaSource | Blob>
  srcdoc?: DOMAttribute<State, string>
  srclang?: DOMAttribute<State, string>
  srcset?: DOMAttribute<State, string>
  start?: DOMAttribute<State, number>
  step?: DOMAttribute<State, string>
  style?: DOMAttribute<State, CSSProperties>
  tabIndex?: DOMAttribute<State, number>
  target?: DOMAttribute<State, string>
  text?: DOMAttribute<State, string>
  title?: DOMAttribute<State, string>
  translate?: DOMAttribute<State, boolean>
  type?: DOMAttribute<State, string>
  useMap?: DOMAttribute<State, string>
  username?: DOMAttribute<State, string>
  value?: DOMAttribute<State, string | number>
  valueAsDate?: DOMAttribute<State, Date | null>
  valueAsNumber?: DOMAttribute<State, number>
  volume?: DOMAttribute<State, number>
  width?: DOMAttribute<State, number | string>
  wrap?: DOMAttribute<State, string>
  zoomAndPan?: DOMAttribute<State, number>
}
