import { DOMAttribute } from './value';
export interface CSSProperties {
    additiveSymbols?: string;
    alignContent?: string;
    alignItems?: string;
    alignSelf?: string;
    all?: string;
    animation?: string;
    animationDelay?: string;
    animationDirection?: string;
    animationDuration?: string;
    animationFillMode?: string;
    animationIterationCount?: string;
    animationName?: string;
    animationPlayState?: string;
    animationTimingFunction?: string;
    backfaceVisibility?: string;
    background?: string;
    backgroundAttachment?: string;
    backgroundBlendMode?: string;
    backgroundClip?: string;
    backgroundColor?: string;
    backgroundImage?: string;
    backgroundOrigin?: string;
    backgroundPosition?: string;
    backgroundRepeat?: string;
    backgroundSize?: string;
    blockSize?: string;
    border?: string;
    borderBlock?: string;
    borderBlockColor?: string;
    borderBlockEnd?: string;
    borderBlockEndColor?: string;
    borderBlockEndStyle?: string;
    borderBlockEndWidth?: string;
    borderBlockStart?: string;
    borderBlockStartColor?: string;
    borderBlockStartStyle?: string;
    borderBlockStartWidth?: string;
    borderBlockStyle?: string;
    borderBlockWidth?: string;
    borderBottom?: string;
    borderBottomColor?: string;
    borderBottomLeftRadius?: string;
    borderBottomRightRadius?: string;
    borderBottomStyle?: string;
    borderBottomWidth?: string;
    borderCollapse?: string;
    borderColor?: string;
    borderEndEndRadius?: string;
    borderEndStartRadius?: string;
    borderImage?: string;
    borderImageOutset?: string;
    borderImageRepeat?: string;
    borderImageSlice?: string;
    borderImageSource?: string;
    borderImageWidth?: string;
    borderInline?: string;
    borderInlineColor?: string;
    borderInlineEnd?: string;
    borderInlineEndColor?: string;
    borderInlineEndStyle?: string;
    borderInlineEndWidth?: string;
    borderInlineStart?: string;
    borderInlineStartColor?: string;
    borderInlineStartStyle?: string;
    borderInlineStartWidth?: string;
    borderInlineStyle?: string;
    borderInlineWidth?: string;
    borderLeft?: string;
    borderLeftColor?: string;
    borderLeftStyle?: string;
    borderLeftWidth?: string;
    borderRadius?: string;
    borderRight?: string;
    borderRightColor?: string;
    borderRightStyle?: string;
    borderRightWidth?: string;
    borderSpacing?: string;
    borderStartEndRadius?: string;
    borderStartStartRadius?: string;
    borderStyle?: string;
    borderTop?: string;
    borderTopColor?: string;
    borderTopLeftRadius?: string;
    borderTopRightRadius?: string;
    borderTopStyle?: string;
    borderTopWidth?: string;
    borderWidth?: string;
    bottom?: string;
    boxDecorationBreak?: string;
    boxShadow?: string;
    boxSizing?: string;
    breakAfter?: string;
    breakBefore?: string;
    breakInside?: string;
    captionSide?: string;
    caretColor?: string;
    clear?: string;
    clip?: string;
    clipPath?: string;
    color?: string;
    colorAdjust?: string;
    columnCount?: string;
    columnFill?: string;
    columnGap?: string;
    columnRule?: string;
    columnRuleColor?: string;
    columnRuleStyle?: string;
    columnRuleWidth?: string;
    columnSpan?: string;
    columnWidth?: string;
    columns?: string;
    content?: string;
    counterIncrement?: string;
    counterReset?: string;
    cursor?: string;
    direction?: string;
    display?: string;
    emptyCells?: string;
    fallback?: string;
    filter?: string;
    flex?: string;
    flexBasis?: string;
    flexDirection?: string;
    flexFlow?: string;
    flexGrow?: string;
    flexShrink?: string;
    flexWrap?: string;
    float?: string;
    font?: string;
    fontFamily?: string;
    fontFeatureSettings?: string;
    fontKerning?: string;
    fontLanguageOverride?: string;
    fontOpticalSizing?: string;
    fontSize?: string;
    fontSizeAdjust?: string;
    fontStretch?: string;
    fontStyle?: string;
    fontSynthesis?: string;
    fontVariant?: string;
    fontVariantAlternates?: string;
    fontVariantCaps?: string;
    fontVariantEastAsian?: string;
    fontVariantLigatures?: string;
    fontVariantNumeric?: string;
    fontVariantPosition?: string;
    fontVariationSettings?: string;
    fontWeight?: string;
    gap?: string;
    grid?: string;
    gridArea?: string;
    gridAutoColumns?: string;
    gridAutoFlow?: string;
    gridAutoRows?: string;
    gridColumn?: string;
    gridColumnEnd?: string;
    gridColumnStart?: string;
    gridRow?: string;
    gridRowEnd?: string;
    gridRowStart?: string;
    gridTemplate?: string;
    gridTemplateAreas?: string;
    gridTemplateColumns?: string;
    gridTemplateRows?: string;
    hangingPunctuation?: string;
    height?: string;
    hyphens?: string;
    imageOrientation?: string;
    imageRendering?: string;
    inlineSize?: string;
    inset?: string;
    insetBlock?: string;
    insetBlockEnd?: string;
    insetBlockStart?: string;
    insetInline?: string;
    insetInlineEnd?: string;
    insetInlineStart?: string;
    isolation?: string;
    justifyContent?: string;
    justifyItems?: string;
    justifySelf?: string;
    left?: string;
    letterSpacing?: string;
    lineBreak?: string;
    lineHeight?: string;
    listStyle?: string;
    listStyleImage?: string;
    listStylePosition?: string;
    listStyleType?: string;
    margin?: string;
    marginBlock?: string;
    marginBlockEnd?: string;
    marginBlockStart?: string;
    marginBottom?: string;
    marginInline?: string;
    marginInlineEnd?: string;
    marginInlineStart?: string;
    marginLeft?: string;
    marginRight?: string;
    marginTop?: string;
    mask?: string;
    maskClip?: string;
    maskComposite?: string;
    maskImage?: string;
    maskMode?: string;
    maskOrigin?: string;
    maskPosition?: string;
    maskRepeat?: string;
    maskSize?: string;
    maskType?: string;
    maxHeight?: string;
    maxWidth?: string;
    maxZoom?: string;
    minBlockSize?: string;
    minHeight?: string;
    minInlineSize?: string;
    minWidth?: string;
    minZoom?: string;
    mixBlendMode?: string;
    negative?: string;
    objectFit?: string;
    objectPosition?: string;
    opacity?: string;
    order?: string;
    orientation?: string;
    orphans?: string;
    outline?: string;
    outlineColor?: string;
    outlineOffset?: string;
    outlineStyle?: string;
    outlineWidth?: string;
    overflow?: string;
    overflowWrap?: string;
    overflowX?: string;
    overflowY?: string;
    pad?: string;
    padding?: string;
    paddingBlock?: string;
    paddingBlockEnd?: string;
    paddingBlockStart?: string;
    paddingBottom?: string;
    paddingInline?: string;
    paddingInlineEnd?: string;
    paddingInlineStart?: string;
    paddingLeft?: string;
    paddingRight?: string;
    paddingTop?: string;
    pageBreakAfter?: string;
    pageBreakBefore?: string;
    pageBreakInside?: string;
    perspective?: string;
    perspectiveOrigin?: string;
    placeContent?: string;
    placeItems?: string;
    pointerEvents?: string;
    position?: string;
    prefix?: string;
    quotes?: string;
    range?: string;
    resize?: string;
    revert?: string;
    right?: string;
    rotate?: string;
    rowGap?: string;
    scale?: string;
    scrollBehavior?: string;
    scrollMargin?: string;
    scrollMarginBlock?: string;
    scrollMarginBlockEnd?: string;
    scrollMarginBlockStart?: string;
    scrollMarginBottom?: string;
    scrollMarginInline?: string;
    scrollMarginInlineEnd?: string;
    scrollMarginInlineStart?: string;
    scrollMarginLeft?: string;
    scrollMarginRight?: string;
    scrollMarginTop?: string;
    scrollPadding?: string;
    scrollPaddingBlock?: string;
    scrollPaddingBlockEnd?: string;
    scrollPaddingBlockStart?: string;
    scrollPaddingBottom?: string;
    scrollPaddingInline?: string;
    scrollPaddingInlineEnd?: string;
    scrollPaddingInlineStart?: string;
    scrollPaddingLeft?: string;
    scrollPaddingRight?: string;
    scrollPaddingTop?: string;
    scrollSnapAlign?: string;
    scrollSnapStop?: string;
    scrollSnapType?: string;
    scrollbarColor?: string;
    scrollbarWidth?: string;
    shapeImageThreshold?: string;
    shapeMargin?: string;
    shapeOutside?: string;
    speakAs?: string;
    src?: string;
    suffix?: string;
    symbols?: string;
    system?: string;
    tabSize?: string;
    tableLayout?: string;
    textAlign?: string;
    textAlignLast?: string;
    textCombineUpright?: string;
    textDecoration?: string;
    textDecorationColor?: string;
    textDecorationLine?: string;
    textDecorationStyle?: string;
    textEmphasis?: string;
    textEmphasisColor?: string;
    textEmphasisPosition?: string;
    textEmphasisStyle?: string;
    textIndent?: string;
    textJustify?: string;
    textOrientation?: string;
    textOverflow?: string;
    textRendering?: string;
    textShadow?: string;
    textTransform?: string;
    textUnderlinePosition?: string;
    top?: string;
    touchAction?: string;
    transform?: string;
    transformBox?: string;
    transformOrigin?: string;
    transformStyle?: string;
    transition?: string;
    transitionDelay?: string;
    transitionDuration?: string;
    transitionProperty?: string;
    transitionTimingFunction?: string;
    translate?: string;
    unicodeBidi?: string;
    unicodeRange?: string;
    unset?: string;
    userZoom?: string;
    verticalAlign?: string;
    visibility?: string;
    whiteSpace?: string;
    widows?: string;
    width?: string;
    willChange?: string;
    wordBreak?: string;
    wordSpacing?: string;
    wordWrap?: string;
    writingMode?: string;
    zIndex?: string;
    zoom?: string;
}
export interface CSSAttributes<State> {
    $additiveSymbols?: DOMAttribute<State, string>;
    $alignContent?: DOMAttribute<State, string>;
    $alignItems?: DOMAttribute<State, string>;
    $alignSelf?: DOMAttribute<State, string>;
    $all?: DOMAttribute<State, string>;
    $animation?: DOMAttribute<State, string>;
    $animationDelay?: DOMAttribute<State, string>;
    $animationDirection?: DOMAttribute<State, string>;
    $animationDuration?: DOMAttribute<State, string>;
    $animationFillMode?: DOMAttribute<State, string>;
    $animationIterationCount?: DOMAttribute<State, string>;
    $animationName?: DOMAttribute<State, string>;
    $animationPlayState?: DOMAttribute<State, string>;
    $animationTimingFunction?: DOMAttribute<State, string>;
    $backfaceVisibility?: DOMAttribute<State, string>;
    $background?: DOMAttribute<State, string>;
    $backgroundAttachment?: DOMAttribute<State, string>;
    $backgroundBlendMode?: DOMAttribute<State, string>;
    $backgroundClip?: DOMAttribute<State, string>;
    $backgroundColor?: DOMAttribute<State, string>;
    $backgroundImage?: DOMAttribute<State, string>;
    $backgroundOrigin?: DOMAttribute<State, string>;
    $backgroundPosition?: DOMAttribute<State, string>;
    $backgroundRepeat?: DOMAttribute<State, string>;
    $backgroundSize?: DOMAttribute<State, string>;
    $blockSize?: DOMAttribute<State, string>;
    $border?: DOMAttribute<State, string>;
    $borderBlock?: DOMAttribute<State, string>;
    $borderBlockColor?: DOMAttribute<State, string>;
    $borderBlockEnd?: DOMAttribute<State, string>;
    $borderBlockEndColor?: DOMAttribute<State, string>;
    $borderBlockEndStyle?: DOMAttribute<State, string>;
    $borderBlockEndWidth?: DOMAttribute<State, string>;
    $borderBlockStart?: DOMAttribute<State, string>;
    $borderBlockStartColor?: DOMAttribute<State, string>;
    $borderBlockStartStyle?: DOMAttribute<State, string>;
    $borderBlockStartWidth?: DOMAttribute<State, string>;
    $borderBlockStyle?: DOMAttribute<State, string>;
    $borderBlockWidth?: DOMAttribute<State, string>;
    $borderBottom?: DOMAttribute<State, string>;
    $borderBottomColor?: DOMAttribute<State, string>;
    $borderBottomLeftRadius?: DOMAttribute<State, string>;
    $borderBottomRightRadius?: DOMAttribute<State, string>;
    $borderBottomStyle?: DOMAttribute<State, string>;
    $borderBottomWidth?: DOMAttribute<State, string>;
    $borderCollapse?: DOMAttribute<State, string>;
    $borderColor?: DOMAttribute<State, string>;
    $borderEndEndRadius?: DOMAttribute<State, string>;
    $borderEndStartRadius?: DOMAttribute<State, string>;
    $borderImage?: DOMAttribute<State, string>;
    $borderImageOutset?: DOMAttribute<State, string>;
    $borderImageRepeat?: DOMAttribute<State, string>;
    $borderImageSlice?: DOMAttribute<State, string>;
    $borderImageSource?: DOMAttribute<State, string>;
    $borderImageWidth?: DOMAttribute<State, string>;
    $borderInline?: DOMAttribute<State, string>;
    $borderInlineColor?: DOMAttribute<State, string>;
    $borderInlineEnd?: DOMAttribute<State, string>;
    $borderInlineEndColor?: DOMAttribute<State, string>;
    $borderInlineEndStyle?: DOMAttribute<State, string>;
    $borderInlineEndWidth?: DOMAttribute<State, string>;
    $borderInlineStart?: DOMAttribute<State, string>;
    $borderInlineStartColor?: DOMAttribute<State, string>;
    $borderInlineStartStyle?: DOMAttribute<State, string>;
    $borderInlineStartWidth?: DOMAttribute<State, string>;
    $borderInlineStyle?: DOMAttribute<State, string>;
    $borderInlineWidth?: DOMAttribute<State, string>;
    $borderLeft?: DOMAttribute<State, string>;
    $borderLeftColor?: DOMAttribute<State, string>;
    $borderLeftStyle?: DOMAttribute<State, string>;
    $borderLeftWidth?: DOMAttribute<State, string>;
    $borderRadius?: DOMAttribute<State, string>;
    $borderRight?: DOMAttribute<State, string>;
    $borderRightColor?: DOMAttribute<State, string>;
    $borderRightStyle?: DOMAttribute<State, string>;
    $borderRightWidth?: DOMAttribute<State, string>;
    $borderSpacing?: DOMAttribute<State, string>;
    $borderStartEndRadius?: DOMAttribute<State, string>;
    $borderStartStartRadius?: DOMAttribute<State, string>;
    $borderStyle?: DOMAttribute<State, string>;
    $borderTop?: DOMAttribute<State, string>;
    $borderTopColor?: DOMAttribute<State, string>;
    $borderTopLeftRadius?: DOMAttribute<State, string>;
    $borderTopRightRadius?: DOMAttribute<State, string>;
    $borderTopStyle?: DOMAttribute<State, string>;
    $borderTopWidth?: DOMAttribute<State, string>;
    $borderWidth?: DOMAttribute<State, string>;
    $bottom?: DOMAttribute<State, string>;
    $boxDecorationBreak?: DOMAttribute<State, string>;
    $boxShadow?: DOMAttribute<State, string>;
    $boxSizing?: DOMAttribute<State, string>;
    $breakAfter?: DOMAttribute<State, string>;
    $breakBefore?: DOMAttribute<State, string>;
    $breakInside?: DOMAttribute<State, string>;
    $captionSide?: DOMAttribute<State, string>;
    $caretColor?: DOMAttribute<State, string>;
    $clear?: DOMAttribute<State, string>;
    $clip?: DOMAttribute<State, string>;
    $clipPath?: DOMAttribute<State, string>;
    $color?: DOMAttribute<State, string>;
    $colorAdjust?: DOMAttribute<State, string>;
    $columnCount?: DOMAttribute<State, string>;
    $columnFill?: DOMAttribute<State, string>;
    $columnGap?: DOMAttribute<State, string>;
    $columnRule?: DOMAttribute<State, string>;
    $columnRuleColor?: DOMAttribute<State, string>;
    $columnRuleStyle?: DOMAttribute<State, string>;
    $columnRuleWidth?: DOMAttribute<State, string>;
    $columnSpan?: DOMAttribute<State, string>;
    $columnWidth?: DOMAttribute<State, string>;
    $columns?: DOMAttribute<State, string>;
    $content?: DOMAttribute<State, string>;
    $counterIncrement?: DOMAttribute<State, string>;
    $counterReset?: DOMAttribute<State, string>;
    $cursor?: DOMAttribute<State, string>;
    $direction?: DOMAttribute<State, string>;
    $display?: DOMAttribute<State, string>;
    $emptyCells?: DOMAttribute<State, string>;
    $fallback?: DOMAttribute<State, string>;
    $filter?: DOMAttribute<State, string>;
    $flex?: DOMAttribute<State, string>;
    $flexBasis?: DOMAttribute<State, string>;
    $flexDirection?: DOMAttribute<State, string>;
    $flexFlow?: DOMAttribute<State, string>;
    $flexGrow?: DOMAttribute<State, string>;
    $flexShrink?: DOMAttribute<State, string>;
    $flexWrap?: DOMAttribute<State, string>;
    $float?: DOMAttribute<State, string>;
    $font?: DOMAttribute<State, string>;
    $fontFamily?: DOMAttribute<State, string>;
    $fontFeatureSettings?: DOMAttribute<State, string>;
    $fontKerning?: DOMAttribute<State, string>;
    $fontLanguageOverride?: DOMAttribute<State, string>;
    $fontOpticalSizing?: DOMAttribute<State, string>;
    $fontSize?: DOMAttribute<State, string>;
    $fontSizeAdjust?: DOMAttribute<State, string>;
    $fontStretch?: DOMAttribute<State, string>;
    $fontStyle?: DOMAttribute<State, string>;
    $fontSynthesis?: DOMAttribute<State, string>;
    $fontVariant?: DOMAttribute<State, string>;
    $fontVariantAlternates?: DOMAttribute<State, string>;
    $fontVariantCaps?: DOMAttribute<State, string>;
    $fontVariantEastAsian?: DOMAttribute<State, string>;
    $fontVariantLigatures?: DOMAttribute<State, string>;
    $fontVariantNumeric?: DOMAttribute<State, string>;
    $fontVariantPosition?: DOMAttribute<State, string>;
    $fontVariationSettings?: DOMAttribute<State, string>;
    $fontWeight?: DOMAttribute<State, string>;
    $gap?: DOMAttribute<State, string>;
    $grid?: DOMAttribute<State, string>;
    $gridArea?: DOMAttribute<State, string>;
    $gridAutoColumns?: DOMAttribute<State, string>;
    $gridAutoFlow?: DOMAttribute<State, string>;
    $gridAutoRows?: DOMAttribute<State, string>;
    $gridColumn?: DOMAttribute<State, string>;
    $gridColumnEnd?: DOMAttribute<State, string>;
    $gridColumnStart?: DOMAttribute<State, string>;
    $gridRow?: DOMAttribute<State, string>;
    $gridRowEnd?: DOMAttribute<State, string>;
    $gridRowStart?: DOMAttribute<State, string>;
    $gridTemplate?: DOMAttribute<State, string>;
    $gridTemplateAreas?: DOMAttribute<State, string>;
    $gridTemplateColumns?: DOMAttribute<State, string>;
    $gridTemplateRows?: DOMAttribute<State, string>;
    $hangingPunctuation?: DOMAttribute<State, string>;
    $height?: DOMAttribute<State, string>;
    $hyphens?: DOMAttribute<State, string>;
    $imageOrientation?: DOMAttribute<State, string>;
    $imageRendering?: DOMAttribute<State, string>;
    $inlineSize?: DOMAttribute<State, string>;
    $inset?: DOMAttribute<State, string>;
    $insetBlock?: DOMAttribute<State, string>;
    $insetBlockEnd?: DOMAttribute<State, string>;
    $insetBlockStart?: DOMAttribute<State, string>;
    $insetInline?: DOMAttribute<State, string>;
    $insetInlineEnd?: DOMAttribute<State, string>;
    $insetInlineStart?: DOMAttribute<State, string>;
    $isolation?: DOMAttribute<State, string>;
    $justifyContent?: DOMAttribute<State, string>;
    $justifyItems?: DOMAttribute<State, string>;
    $justifySelf?: DOMAttribute<State, string>;
    $left?: DOMAttribute<State, string>;
    $letterSpacing?: DOMAttribute<State, string>;
    $lineBreak?: DOMAttribute<State, string>;
    $lineHeight?: DOMAttribute<State, string>;
    $listStyle?: DOMAttribute<State, string>;
    $listStyleImage?: DOMAttribute<State, string>;
    $listStylePosition?: DOMAttribute<State, string>;
    $listStyleType?: DOMAttribute<State, string>;
    $margin?: DOMAttribute<State, string>;
    $marginBlock?: DOMAttribute<State, string>;
    $marginBlockEnd?: DOMAttribute<State, string>;
    $marginBlockStart?: DOMAttribute<State, string>;
    $marginBottom?: DOMAttribute<State, string>;
    $marginInline?: DOMAttribute<State, string>;
    $marginInlineEnd?: DOMAttribute<State, string>;
    $marginInlineStart?: DOMAttribute<State, string>;
    $marginLeft?: DOMAttribute<State, string>;
    $marginRight?: DOMAttribute<State, string>;
    $marginTop?: DOMAttribute<State, string>;
    $mask?: DOMAttribute<State, string>;
    $maskClip?: DOMAttribute<State, string>;
    $maskComposite?: DOMAttribute<State, string>;
    $maskImage?: DOMAttribute<State, string>;
    $maskMode?: DOMAttribute<State, string>;
    $maskOrigin?: DOMAttribute<State, string>;
    $maskPosition?: DOMAttribute<State, string>;
    $maskRepeat?: DOMAttribute<State, string>;
    $maskSize?: DOMAttribute<State, string>;
    $maskType?: DOMAttribute<State, string>;
    $maxHeight?: DOMAttribute<State, string>;
    $maxWidth?: DOMAttribute<State, string>;
    $maxZoom?: DOMAttribute<State, string>;
    $minBlockSize?: DOMAttribute<State, string>;
    $minHeight?: DOMAttribute<State, string>;
    $minInlineSize?: DOMAttribute<State, string>;
    $minWidth?: DOMAttribute<State, string>;
    $minZoom?: DOMAttribute<State, string>;
    $mixBlendMode?: DOMAttribute<State, string>;
    $negative?: DOMAttribute<State, string>;
    $objectFit?: DOMAttribute<State, string>;
    $objectPosition?: DOMAttribute<State, string>;
    $opacity?: DOMAttribute<State, string>;
    $order?: DOMAttribute<State, string>;
    $orientation?: DOMAttribute<State, string>;
    $orphans?: DOMAttribute<State, string>;
    $outline?: DOMAttribute<State, string>;
    $outlineColor?: DOMAttribute<State, string>;
    $outlineOffset?: DOMAttribute<State, string>;
    $outlineStyle?: DOMAttribute<State, string>;
    $outlineWidth?: DOMAttribute<State, string>;
    $overflow?: DOMAttribute<State, string>;
    $overflowWrap?: DOMAttribute<State, string>;
    $overflowX?: DOMAttribute<State, string>;
    $overflowY?: DOMAttribute<State, string>;
    $pad?: DOMAttribute<State, string>;
    $padding?: DOMAttribute<State, string>;
    $paddingBlock?: DOMAttribute<State, string>;
    $paddingBlockEnd?: DOMAttribute<State, string>;
    $paddingBlockStart?: DOMAttribute<State, string>;
    $paddingBottom?: DOMAttribute<State, string>;
    $paddingInline?: DOMAttribute<State, string>;
    $paddingInlineEnd?: DOMAttribute<State, string>;
    $paddingInlineStart?: DOMAttribute<State, string>;
    $paddingLeft?: DOMAttribute<State, string>;
    $paddingRight?: DOMAttribute<State, string>;
    $paddingTop?: DOMAttribute<State, string>;
    $pageBreakAfter?: DOMAttribute<State, string>;
    $pageBreakBefore?: DOMAttribute<State, string>;
    $pageBreakInside?: DOMAttribute<State, string>;
    $perspective?: DOMAttribute<State, string>;
    $perspectiveOrigin?: DOMAttribute<State, string>;
    $placeContent?: DOMAttribute<State, string>;
    $placeItems?: DOMAttribute<State, string>;
    $pointerEvents?: DOMAttribute<State, string>;
    $position?: DOMAttribute<State, string>;
    $prefix?: DOMAttribute<State, string>;
    $quotes?: DOMAttribute<State, string>;
    $range?: DOMAttribute<State, string>;
    $resize?: DOMAttribute<State, string>;
    $revert?: DOMAttribute<State, string>;
    $right?: DOMAttribute<State, string>;
    $rotate?: DOMAttribute<State, string>;
    $rowGap?: DOMAttribute<State, string>;
    $scale?: DOMAttribute<State, string>;
    $scrollBehavior?: DOMAttribute<State, string>;
    $scrollMargin?: DOMAttribute<State, string>;
    $scrollMarginBlock?: DOMAttribute<State, string>;
    $scrollMarginBlockEnd?: DOMAttribute<State, string>;
    $scrollMarginBlockStart?: DOMAttribute<State, string>;
    $scrollMarginBottom?: DOMAttribute<State, string>;
    $scrollMarginInline?: DOMAttribute<State, string>;
    $scrollMarginInlineEnd?: DOMAttribute<State, string>;
    $scrollMarginInlineStart?: DOMAttribute<State, string>;
    $scrollMarginLeft?: DOMAttribute<State, string>;
    $scrollMarginRight?: DOMAttribute<State, string>;
    $scrollMarginTop?: DOMAttribute<State, string>;
    $scrollPadding?: DOMAttribute<State, string>;
    $scrollPaddingBlock?: DOMAttribute<State, string>;
    $scrollPaddingBlockEnd?: DOMAttribute<State, string>;
    $scrollPaddingBlockStart?: DOMAttribute<State, string>;
    $scrollPaddingBottom?: DOMAttribute<State, string>;
    $scrollPaddingInline?: DOMAttribute<State, string>;
    $scrollPaddingInlineEnd?: DOMAttribute<State, string>;
    $scrollPaddingInlineStart?: DOMAttribute<State, string>;
    $scrollPaddingLeft?: DOMAttribute<State, string>;
    $scrollPaddingRight?: DOMAttribute<State, string>;
    $scrollPaddingTop?: DOMAttribute<State, string>;
    $scrollSnapAlign?: DOMAttribute<State, string>;
    $scrollSnapStop?: DOMAttribute<State, string>;
    $scrollSnapType?: DOMAttribute<State, string>;
    $scrollbarColor?: DOMAttribute<State, string>;
    $scrollbarWidth?: DOMAttribute<State, string>;
    $shapeImageThreshold?: DOMAttribute<State, string>;
    $shapeMargin?: DOMAttribute<State, string>;
    $shapeOutside?: DOMAttribute<State, string>;
    $speakAs?: DOMAttribute<State, string>;
    $src?: DOMAttribute<State, string>;
    $suffix?: DOMAttribute<State, string>;
    $symbols?: DOMAttribute<State, string>;
    $system?: DOMAttribute<State, string>;
    $tabSize?: DOMAttribute<State, string>;
    $tableLayout?: DOMAttribute<State, string>;
    $textAlign?: DOMAttribute<State, string>;
    $textAlignLast?: DOMAttribute<State, string>;
    $textCombineUpright?: DOMAttribute<State, string>;
    $textDecoration?: DOMAttribute<State, string>;
    $textDecorationColor?: DOMAttribute<State, string>;
    $textDecorationLine?: DOMAttribute<State, string>;
    $textDecorationStyle?: DOMAttribute<State, string>;
    $textEmphasis?: DOMAttribute<State, string>;
    $textEmphasisColor?: DOMAttribute<State, string>;
    $textEmphasisPosition?: DOMAttribute<State, string>;
    $textEmphasisStyle?: DOMAttribute<State, string>;
    $textIndent?: DOMAttribute<State, string>;
    $textJustify?: DOMAttribute<State, string>;
    $textOrientation?: DOMAttribute<State, string>;
    $textOverflow?: DOMAttribute<State, string>;
    $textRendering?: DOMAttribute<State, string>;
    $textShadow?: DOMAttribute<State, string>;
    $textTransform?: DOMAttribute<State, string>;
    $textUnderlinePosition?: DOMAttribute<State, string>;
    $top?: DOMAttribute<State, string>;
    $touchAction?: DOMAttribute<State, string>;
    $transform?: DOMAttribute<State, string>;
    $transformBox?: DOMAttribute<State, string>;
    $transformOrigin?: DOMAttribute<State, string>;
    $transformStyle?: DOMAttribute<State, string>;
    $transition?: DOMAttribute<State, string>;
    $transitionDelay?: DOMAttribute<State, string>;
    $transitionDuration?: DOMAttribute<State, string>;
    $transitionProperty?: DOMAttribute<State, string>;
    $transitionTimingFunction?: DOMAttribute<State, string>;
    $translate?: DOMAttribute<State, string>;
    $unicodeBidi?: DOMAttribute<State, string>;
    $unicodeRange?: DOMAttribute<State, string>;
    $unset?: DOMAttribute<State, string>;
    $userZoom?: DOMAttribute<State, string>;
    $verticalAlign?: DOMAttribute<State, string>;
    $visibility?: DOMAttribute<State, string>;
    $whiteSpace?: DOMAttribute<State, string>;
    $widows?: DOMAttribute<State, string>;
    $width?: DOMAttribute<State, string>;
    $willChange?: DOMAttribute<State, string>;
    $wordBreak?: DOMAttribute<State, string>;
    $wordSpacing?: DOMAttribute<State, string>;
    $wordWrap?: DOMAttribute<State, string>;
    $writingMode?: DOMAttribute<State, string>;
    $zIndex?: DOMAttribute<State, string>;
    $zoom?: DOMAttribute<State, string>;
}
export declare const cssMapper: {
    additiveSymbols: string;
    alignContent: string;
    alignItems: string;
    alignSelf: string;
    animationDelay: string;
    animationDirection: string;
    animationDuration: string;
    animationFillMode: string;
    animationIterationCount: string;
    animationName: string;
    animationPlayState: string;
    animationTimingFunction: string;
    backfaceVisibility: string;
    backgroundAttachment: string;
    backgroundBlendMode: string;
    backgroundClip: string;
    backgroundColor: string;
    backgroundImage: string;
    backgroundOrigin: string;
    backgroundPosition: string;
    backgroundRepeat: string;
    backgroundSize: string;
    blockSize: string;
    borderBlock: string;
    borderBlockColor: string;
    borderBlockEnd: string;
    borderBlockEndColor: string;
    borderBlockEndStyle: string;
    borderBlockEndWidth: string;
    borderBlockStart: string;
    borderBlockStartColor: string;
    borderBlockStartStyle: string;
    borderBlockStartWidth: string;
    borderBlockStyle: string;
    borderBlockWidth: string;
    borderBottom: string;
    borderBottomColor: string;
    borderBottomLeftRadius: string;
    borderBottomRightRadius: string;
    borderBottomStyle: string;
    borderBottomWidth: string;
    borderCollapse: string;
    borderColor: string;
    borderEndEndRadius: string;
    borderEndStartRadius: string;
    borderImage: string;
    borderImageOutset: string;
    borderImageRepeat: string;
    borderImageSlice: string;
    borderImageSource: string;
    borderImageWidth: string;
    borderInline: string;
    borderInlineColor: string;
    borderInlineEnd: string;
    borderInlineEndColor: string;
    borderInlineEndStyle: string;
    borderInlineEndWidth: string;
    borderInlineStart: string;
    borderInlineStartColor: string;
    borderInlineStartStyle: string;
    borderInlineStartWidth: string;
    borderInlineStyle: string;
    borderInlineWidth: string;
    borderLeft: string;
    borderLeftColor: string;
    borderLeftStyle: string;
    borderLeftWidth: string;
    borderRadius: string;
    borderRight: string;
    borderRightColor: string;
    borderRightStyle: string;
    borderRightWidth: string;
    borderSpacing: string;
    borderStartEndRadius: string;
    borderStartStartRadius: string;
    borderStyle: string;
    borderTop: string;
    borderTopColor: string;
    borderTopLeftRadius: string;
    borderTopRightRadius: string;
    borderTopStyle: string;
    borderTopWidth: string;
    borderWidth: string;
    boxDecorationBreak: string;
    boxShadow: string;
    boxSizing: string;
    breakAfter: string;
    breakBefore: string;
    breakInside: string;
    captionSide: string;
    caretColor: string;
    clipPath: string;
    colorAdjust: string;
    columnCount: string;
    columnFill: string;
    columnGap: string;
    columnRule: string;
    columnRuleColor: string;
    columnRuleStyle: string;
    columnRuleWidth: string;
    columnSpan: string;
    columnWidth: string;
    counterIncrement: string;
    counterReset: string;
    emptyCells: string;
    flexBasis: string;
    flexDirection: string;
    flexFlow: string;
    flexGrow: string;
    flexShrink: string;
    flexWrap: string;
    fontFamily: string;
    fontFeatureSettings: string;
    fontKerning: string;
    fontLanguageOverride: string;
    fontOpticalSizing: string;
    fontSize: string;
    fontSizeAdjust: string;
    fontStretch: string;
    fontStyle: string;
    fontSynthesis: string;
    fontVariant: string;
    fontVariantAlternates: string;
    fontVariantCaps: string;
    fontVariantEastAsian: string;
    fontVariantLigatures: string;
    fontVariantNumeric: string;
    fontVariantPosition: string;
    fontVariationSettings: string;
    fontWeight: string;
    gridArea: string;
    gridAutoColumns: string;
    gridAutoFlow: string;
    gridAutoRows: string;
    gridColumn: string;
    gridColumnEnd: string;
    gridColumnStart: string;
    gridRow: string;
    gridRowEnd: string;
    gridRowStart: string;
    gridTemplate: string;
    gridTemplateAreas: string;
    gridTemplateColumns: string;
    gridTemplateRows: string;
    hangingPunctuation: string;
    imageOrientation: string;
    imageRendering: string;
    inlineSize: string;
    insetBlock: string;
    insetBlockEnd: string;
    insetBlockStart: string;
    insetInline: string;
    insetInlineEnd: string;
    insetInlineStart: string;
    justifyContent: string;
    justifyItems: string;
    justifySelf: string;
    letterSpacing: string;
    lineBreak: string;
    lineHeight: string;
    listStyle: string;
    listStyleImage: string;
    listStylePosition: string;
    listStyleType: string;
    marginBlock: string;
    marginBlockEnd: string;
    marginBlockStart: string;
    marginBottom: string;
    marginInline: string;
    marginInlineEnd: string;
    marginInlineStart: string;
    marginLeft: string;
    marginRight: string;
    marginTop: string;
    maskClip: string;
    maskComposite: string;
    maskImage: string;
    maskMode: string;
    maskOrigin: string;
    maskPosition: string;
    maskRepeat: string;
    maskSize: string;
    maskType: string;
    maxHeight: string;
    maxWidth: string;
    maxZoom: string;
    minBlockSize: string;
    minHeight: string;
    minInlineSize: string;
    minWidth: string;
    minZoom: string;
    mixBlendMode: string;
    objectFit: string;
    objectPosition: string;
    outlineColor: string;
    outlineOffset: string;
    outlineStyle: string;
    outlineWidth: string;
    overflowWrap: string;
    overflowX: string;
    overflowY: string;
    paddingBlock: string;
    paddingBlockEnd: string;
    paddingBlockStart: string;
    paddingBottom: string;
    paddingInline: string;
    paddingInlineEnd: string;
    paddingInlineStart: string;
    paddingLeft: string;
    paddingRight: string;
    paddingTop: string;
    pageBreakAfter: string;
    pageBreakBefore: string;
    pageBreakInside: string;
    perspectiveOrigin: string;
    placeContent: string;
    placeItems: string;
    pointerEvents: string;
    rowGap: string;
    scrollBehavior: string;
    scrollMargin: string;
    scrollMarginBlock: string;
    scrollMarginBlockEnd: string;
    scrollMarginBlockStart: string;
    scrollMarginBottom: string;
    scrollMarginInline: string;
    scrollMarginInlineEnd: string;
    scrollMarginInlineStart: string;
    scrollMarginLeft: string;
    scrollMarginRight: string;
    scrollMarginTop: string;
    scrollPadding: string;
    scrollPaddingBlock: string;
    scrollPaddingBlockEnd: string;
    scrollPaddingBlockStart: string;
    scrollPaddingBottom: string;
    scrollPaddingInline: string;
    scrollPaddingInlineEnd: string;
    scrollPaddingInlineStart: string;
    scrollPaddingLeft: string;
    scrollPaddingRight: string;
    scrollPaddingTop: string;
    scrollSnapAlign: string;
    scrollSnapStop: string;
    scrollSnapType: string;
    scrollbarColor: string;
    scrollbarWidth: string;
    shapeImageThreshold: string;
    shapeMargin: string;
    shapeOutside: string;
    speakAs: string;
    tabSize: string;
    tableLayout: string;
    textAlign: string;
    textAlignLast: string;
    textCombineUpright: string;
    textDecoration: string;
    textDecorationColor: string;
    textDecorationLine: string;
    textDecorationStyle: string;
    textEmphasis: string;
    textEmphasisColor: string;
    textEmphasisPosition: string;
    textEmphasisStyle: string;
    textIndent: string;
    textJustify: string;
    textOrientation: string;
    textOverflow: string;
    textRendering: string;
    textShadow: string;
    textTransform: string;
    textUnderlinePosition: string;
    touchAction: string;
    transformBox: string;
    transformOrigin: string;
    transformStyle: string;
    transitionDelay: string;
    transitionDuration: string;
    transitionProperty: string;
    transitionTimingFunction: string;
    unicodeBidi: string;
    unicodeRange: string;
    userZoom: string;
    verticalAlign: string;
    whiteSpace: string;
    willChange: string;
    wordBreak: string;
    wordSpacing: string;
    wordWrap: string;
    writingMode: string;
    zIndex: string;
};
//# sourceMappingURL=css_properties.d.ts.map